/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.kelompok8.view;

/**
 *
 * @author Acer
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(232, 61, 141));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setText("LOGIN");
        login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 170, 60));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel4.setText("USERNAME");
        login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 140, 40));

        txtNama.setEditable(false);
        txtNama.setBackground(new java.awt.Color(232, 61, 141));
        txtNama.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        txtNama.setText("Masukkan username anda");
        txtNama.setBorder(null);
        login.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 230, 20));
        login.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 230, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok8/images/user.png"))); // NOI18N
        login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 40, 40));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel5.setText("PASSWORD");
        login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 140, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok8/images/Password.png"))); // NOI18N
        login.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, 40));
        login.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 230, 10));

        txtPass.setBackground(new java.awt.Color(232, 61, 141));
        txtPass.setText("jPasswordField1");
        txtPass.setBorder(null);
        login.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 230, 20));

        btnLogin.setBackground(new java.awt.Color(232, 61, 141));
        btnLogin.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        btnLogin.setText("LOGIN");
        login.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 230, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok8/images/Salon Background.png"))); // NOI18N
        login.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 300));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        jLabel2.setText("Gapunya akun? Register disini");
        login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 160, -1));

        bgPanel.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new View().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel login;
    private javax.swing.JTextField txtNama;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
